### ISSUE TITLE
早速要望

### ISSUE THREAD

**Issue by ezvfx** [tm8r/MayaRecentFilesPlus#2]
配布して頂き有難う御座います。早速使用しまして大変重宝しています。

二点要望がありまして
・ビューポートもアクティブに出来ると嬉しい
・スクリプトエディタがアクティブになると効かないので効く様になると嬉しい

1点バグ報告
・選べるウィンドウが一つ少ないです。(2018.5)

以上、お知らせまで

**Comment by tm8r** [comment]
ご要望ありがとうございます！

> ・ビューポートもアクティブに出来ると嬉しい

対応します

> 選べるウィンドウが一つ少ないです。(2018.5)

アクティブなウィンドウのことあれば、そちらは現在ビューポートのように除外対象になっているので対応します

> ・スクリプトエディタがアクティブになると効かないので効く様になると嬉しい

こちら認識済みなのですが、すぐ解決できず一旦ファーストリリースした形になるので、引き続き対応可能か調査します
Maya標準のホットキーも同じ挙動をするので、仕様かなという気はしています…😇

**Comment by tm8r** [comment]
ブログからのissueの誘導リポジトリが間違ってました…
以下に移行しますー
https://github.com/tm8r/MayaWindowSwitcher/issues
